---
- name: 配置主机名
  shell: "hostname {{ inventory_hostname }}"

- name: systemctl daemon-reexec
  shell: 'systemctl daemon-reexec'
  retries: 2
  delay: 1
  tags: system_conf

- name: systemctl daemon-reload
  shell: 'systemctl daemon-reload'
  retries: 2
  delay: 1
  tags: system_conf

- name: 重启 rc.local 服务
  service: name=rc-local state=restarted

- name: 修改运行时内核参数
  shell: 'sysctl -p'
  tags: sysctl_conf

- name: 重启 sshd 服务
  service: name=sshd state=restarted

- name: 禁用 swap分区
  shell: "swapoff -a"
  tags: swap

- name: 设置本机所属的时区为上海
  shell: "echo 'Asia/Shanghai' > /etc/timezone"
  tags: timezone

