#SPDX-License-Identifier: MIT-0
---
# handlers file for kubernetes

- name: apt update_cache
  ansible.builtin.apt:
    update_cache: yes

- name: Restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    enabled: true