---

# 加载内核模块 开始
- name: create kernel module
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: '0644'

- name: Load kernel modules
  ansible.builtin.shell: |
    modprobe overlay
    modprobe br_netfilter
# 加载内核模块 结束



#  网桥过滤及内核转发配置 开始
- name: Bridge filtering and kernel forwarding configuration
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-arptables = 1
      net.ipv4.ip_forward = 1
    mode: '0644'

- name: Apply all sysctl settings
  ansible.builtin.command:
    cmd: sysctl --system

# 网桥过滤及内核转发配置 结束


# 安装负载均衡相关工具
- name: Install ipset and ipvsadm
  ansible.builtin.package:
    name:
      - ipset
      - ipvsadm
    state: present

- name: Create /etc/modules-load.d/ipvs.conf with required kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/ipvs.conf
    content: |
      ip_vs
      ip_vs_rr
      ip_vs_wrr
      ip_vs_sh
      nf_conntrack
    mode: '0644'

- name: Create ipvs.sh script to load kernel modules
  ansible.builtin.copy:
    dest: /usr/local/bin/ipvs.sh
    content: |
      #!/bin/bash
      modprobe -- ip_vs
      modprobe -- ip_vs_rr
      modprobe -- ip_vs_wrr
      modprobe -- ip_vs_sh
      modprobe -- nf_conntrack
    mode: '0755'

- name: Execute ipvs.sh to load kernel modules immediately
  ansible.builtin.command: /usr/local/bin/ipvs.sh
#  安装负载均衡相关工具 结束

# 关闭 swap 开始
- name: Disable swap
  ansible.builtin.command: swapoff -a
  
- name: Ensure swap is disabled in /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*'
    state: absent
# 关闭 swap 结束

